### ISSUE TITLE
[Feature Request]: Agent component waiting for multiple pre-components

### ISSUE THREAD

**Issue by zigerZZZ** [infiniflow/ragflow#10336]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Is your feature request related to a problem?

```Markdown
I put an outcome of an Agent component into different 2 branches. And I want to merge the 2 outcomes at last.
However, the 2 branches have different process time. After the faster one complete, the merge component will start and return. Besides, after the later one complete, the merge component will start again.
```

### Describe the feature you'd like

the merge component will start after both 2 pre-component complete.

### Describe implementation you've considered

Giving the component a param to waiting those pre-component.

Or check the inputs, do not start the process if one of inputs is `None`

### Documentation, adoption, use case

```Markdown

```

### Additional information

the component in the red box has 2 pre-components, and I want it start after the pre-components compelet.

<img width="1920" height="953" alt="Image" src="https://github.com/user-attachments/assets/67c6d817-8196-4235-8a02-880188e23f46" />

**Comment by ZhenhangTung** [comment]
I believe it's a bug we've fixed in https://github.com/infiniflow/ragflow/releases/tag/v0.20.5

> duplicate summarization of parallel execution results

Gotta take a deeper look, and thanks for the report.  btw, which version are you using?

**Comment by zigerZZZ** [comment]
@ZhenhangTung thanks for your reply.

I'm using the docker image `RAGFLOW_IMAGE=infiniflow/ragflow:latest-slim`

I create this agent at v0.20.4 it's before v0.20.5

and I update the docker images several days ago 

```shell
REPOSITORY                                            TAG                            IMAGE ID       CREATED         SIZE
infiniflow/ragflow                                    latest-slim                    762328db33cf   3 days ago      7.08GB
```

**Comment by zigerZZZ** [comment]
With docker images version `v0.20.5-87-gbd94b5df slim` and `v0.20.5 slim`, this bug still exists.

Here we see the arg None output `None in args` in the final outcome.(Actually, make the arg None returns empty str is a temporary solution)

<img width="1920" height="953" alt="Image" src="https://github.com/user-attachments/assets/a4a3ea4f-e586-43aa-a68d-7352172e54e3" />

**Comment by ZhenhangTung** [comment]
Will forward it to our team. Thx!

**Comment by redredrrred** [comment]
Same here, the faster path triggered the agent node which i use for summarization, then it directly generated the response. I want the summarization node to wait until all different paths have completed.
