### ISSUE TITLE
[Question]: Has anyone used an ASGI server (e.g. uvicorn) directly in production?

### ISSUE THREAD

**Issue by davidlcarrascal** [infiniflow/ragflow#11786]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Describe your problem

It’s hard to use Ragflow in production right now because when a user makes a request, the whole system just keeps processing and waits to finish that first call.

I’d like to deploy it with Docker using Uvicorn or Hypercorn using workers, but those dependencies aren’t installed in the image.

**Comment by KevinHuSh** [comment]
You could pull `nightly` version of docker image. The blocking issue is fixed there.

**Comment by davidlcarrascal** [comment]
Thanks @KevinHuSh! Just to confirm, is the fix included in the nightly image or only in the latest tag?
I’ve pulled the nightly image and I’m still seeing the same issue, so I want to be sure I’m using the correct version.

**Comment by davidlcarrascal** [comment]
My situation is as follows, I have everything running in Docker with four workers. When I send a request through the API, the system freezes and won't accept any new requests until the first one finishes. I know the workers are being used for ingestion, but is it possible they're not being used for the API calls?

**Comment by KevinHuSh** [comment]
Could you specify which action will cause blocking?

**Comment by davidlcarrascal** [comment]
@KevinHuSh Yes, I could.

 Here is my flow:

- First, I create a chat assistant:

`POST /api/v1/chats`
```json

{
 ...
}
```

- Then, I create a session for that chat assistant:

`POST /api/v1/chats/${assistant.ragflow_chat_id}/sessions`

```json

{
  "name": "New conversation"
}
```

- Finally, I send a completion request with a question:

`POST /api/v1/chats/{chat_id}/completions`


```json
{
  "question": "<QUESTION>",
  "stream": false,
  "session_id": "<ID>"
}
```


The issue is that when I send one completion and then try to send another one at the same time, the system is blocked: it doesn’t process the second request until the first one has finished.

Ideally, I’d like to use the system in an asynchronous way and be able to have multiple completion calls in progress at the same time.

**Comment by KevinHuSh** [comment]
I filed a PR. Please have a try.

**Comment by davidlcarrascal** [comment]
Thanks @KevinHuSh, I will test in the next nightly build.
