### ISSUE TITLE
[Question]: Docx parse erroe

### ISSUE THREAD

**Issue by wanyuks** [infiniflow/ragflow#1711]
### Describe your problem

When I upload a docx file and parse it, there is a error.
```
[ERROR]Internal server error: not enough values to unpack (expected 2, got 0)
```

Perhaps this is related to the content of my file. Due to certain reasons, my docx file is composed of images pieced together, with each page featuring an image filled with text, representing the official content like this:

![image](https://github.com/user-attachments/assets/6d06a87e-fced-48b5-8ce4-f4526f17a68e)

Is there any way to parse these files using Ragflow?

**Comment by guoyuhao2330** [comment]
fixed

**Comment by wanyuks** [comment]
> fixed

The pr just fixed error occured, the paser still can't extract any text.
