### ISSUE TITLE
[Question]:run ragflow as a chatbot on my website

### ISSUE THREAD

**Issue by monkrus** [infiniflow/ragflow#3429]
### Describe your problem

I would like to run ragflow as a chatbot on my website using my own knowledgebase. Thinking of deploying Docker image on Amazon ECR and exposing the API endpoint to integrate. Is there a better way to run it?

**Comment by KevinHuSh** [comment]
No better way for now.

**Comment by kdta91** [comment]
For our demo we deployed RAGFlow on an EC2 instance.

As for integration, your option for now is to just make use of the [HTTP API](https://ragflow.io/docs/dev/http_api_reference) and handle the session creation on your interface.

**Comment by lexiconlp** [comment]
> For our demo we deployed RAGFlow on an EC2 instance.
> 
> As for integration, your option for now is to just make use of the [HTTP API](https://ragflow.io/docs/dev/http_api_reference) and handle the session creation on your interface.

I create a EC2 instance @kdta91 but I cannot connect to the port from public IP. How you deploy exactly ? 

I run docker-compose in a EC2 instance + add tcp rule for 9380 port, but still not working.
