### ISSUE TITLE
[Question]: Can't use Generate component as the input of Retrieval component in agent

### ISSUE THREAD

**Issue by chenbbc** [infiniflow/ragflow#6119]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Describe your problem

I encountered an issue when using the agent module in Ragflow. This problem did not occur in version 0.16 but started appearing in version 0.17. When using the generate component as the input for the Retrieval component during knowledge base searches, the search results are empty. However, if I use interact directly as the input, the knowledge base can return results.

For example, when searching for information related to January, if I input the keyword "January" directly into interact, I can get relevant results. But if I use generate to produce "January" as the input for Retrieval, the search returns nothing.

How can I resolve this issue?

**Comment by chenbbc** [comment]
This issue mainly occurs when placing the Retrieval component inside a loop.

**Comment by KevinHuSh** [comment]
About the retrieval, we've fixed some bugs laterly.
What about pulling the `nightly` version of docker image?

**Comment by chenbbc** [comment]
Thank you for your reply. I pulled the nightly version（0.17.2-26-g89a69eed slim）, but the problem is still the same.

**Comment by hero8152** [comment]
我感觉是我遇到的那个格式问题，比方说你输入的文本里面有换行或者\n，他就会出现截断。比方说你的输入是123/n45，他就只检索前面的123。会出现三种情况，一个是文本太少例如一个字符就会直接报错erro，一种是返回空结果，一种是返回知识库无结果。

**Comment by chenbbc** [comment]
最新的nightly版本确实解决掉了，更新后已经不出现这一问题了，谢谢答复。
