### ISSUE TITLE
[Bug]: In chat mode, set the similarity and click Save to set it to 0.2

### ISSUE THREAD

**Issue by bilingzhi05** [infiniflow/ragflow#9818]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### RAGFlow workspace code commit ID

NA

### RAGFlow image version

 v0.20.4 slim

### Other environment information

```Markdown

```

### Actual behavior

In chat mode, set the similarity and click Save to set it to 0.2
聊天模式中，设置了相似度，点击保存后设置成0.2

<img width="391" height="606" alt="Image" src="https://github.com/user-attachments/assets/d6c4b13a-e0f7-4e95-825e-53eae7f7c67f" />

### Steps to reproduce

```Markdown
聊天模式中，设置了相似度，点击保存后强制设置成0.2
```

**Comment by fivvvvvv** [comment]
yes,I also encountered this problem.

**Comment by fivvvvvv** [comment]
At present, I can only choose to use 'api' to bypass this problem.

**Comment by dcc123456** [comment]
@bilingzhi05 @wuhaozuishuai  This bug has been fixed in #9821, Welcome to get the latest code to experience it.

**Comment by gymm-betrayer** [comment]
> [@bilingzhi05](https://github.com/bilingzhi05) [@wuhaozuishuai](https://github.com/wuhaozuishuai) This bug has been fixed in [#9821](https://github.com/infiniflow/ragflow/pull/9821), Welcome to get the latest code to experience it.

This issue doesn't seem to be solved, and I'm still having this issue now

**Comment by dcc123456** [comment]
@gymm-betrayer  We will release a new version tomorrow, you can update to experience it
